# github_dark_dimmed kanagawa mellow nightfox penumbra+ rose_pine rose_pine_moon
theme = "kanagawa"

[editor]
line-number = "relative"
mouse = false

[editor.statusline]
right = ["version-control", "spacer", "diagnostics", "selections", "position", "file-encoding", "file-line-ending"]

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = true
